icons = "awesome"

[theme]
name = "bad-wolf"

[theme.overrides]
idle_bg = "#2d2d2d"
info_bg = "#6699cc"
good_bg = "#99cc99"
warning_bg = "#ffcc66"
critical_bg = "#f2777a"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"
chip = "*-isa-*"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"